version: "3"
services:
  web:
    build: ./app
    ports: ['80:5000']
    volumes: ['./app:/app']
    restart: always

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080